### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by StatML** [apple2373/chainer_caption_generation#1]

**Comment by apple2373** [comment]
Hi, I don't know why you closed the issue, but hope that means you solved it.

I prepared a ubuntu virtual machine and tried to reproduce, but I couldn't. I was able to generate a caption for a new image. I think if you install Anaconda, there should be no problems.  This is the screen recording of what I did. You can do it on the same way. 

https://drive.google.com/file/d/0B046sNk0DhCDUkpwblZPME1vQzg/edit
