### ISSUE TITLE
pickle

### ISSUE THREAD

**Issue by h2mysterious** [apple2373/chainer_caption_generation#2]
hello
I installed the environment and I downloaded the data, I just want to have captions, but when I run
generate_caption.py python -i ../images/test_image.jpg
I have this error
loading vocab
caffe loading models
Traceback (most recent call last):
   File "generate_caption.py", line 78, in <module>
     func = pickle.load (f)
ValueError: insecure string pickle

can you help me

**Comment by apple2373** [comment]
Sorry, I could not reproduce your error. 

The correct command is this (well, I guess this is only typo.)
python generate_caption.py  -i ../images/test_image.jpg

Also, maybe there is an error when downloading files, so it might fix the error if you download the file again.

**Comment by h2mysterious** [comment]
thanks, your advice helped me, effectively the problem was with downloading part. so i just re-downloaded the file.
